using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoftwareSuite.Models.Certificate
{
    public class ODCTrSheetData
    {
        public string SNO { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string FNAME { get; set; }
        public string COURSE { get; set; }
        public string CEN { get; set; }
        public string CEN_NAME { get; set; }
        public string CEN_ADDRESS { get; set; }
        public string BR { get; set; }
        public string BRANCH_NAME { get; set; }
        public string MONTH_YEAR { get; set; }
        public string PIN { get; set; }
        public string DURATION { get; set; }
        public string CLASS { get; set; }
        public string MAX_MARKS_1YR { get; set; }
        public string TOTAL1 { get; set; }
        public string TOTAL1_25 { get; set; }
        public string MAX_MARKS_3SEM { get; set; }
        public string TOTAL3S { get; set; }
        public string MAX_MARKS_4SEM { get; set; }
        public string TOTAL4S { get; set; }
        public string MAX_MARKS_5SEM { get; set; }
        public string TOTAL5S { get; set; }
        public string MAX_MARKS_6SEM { get; set; }
        public string TOTAL6S { get; set; }
        public string MAX_MARKS_7SEM { get; set; }
        public string TOTAL7S { get; set; }
        public string GRAND_TOTAL { get; set; }
        public string PER { get; set; }
        public string DAY { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string REMARKS { get; set; }
        public bool CertificateIssued { get; set; }
        public string scheme { get; set; }
        public string MAX_MARKS_1SEM { get; set; }
        public string TOTAL1S { get; set; }
        public string TOTAL1S_25 { get; set; }
        public string MAX_MARKS_2SEM { get; set; }
        public string TOTAL2S { get; set; }
        public string TOTAL2S_25 { get; set; }
    }
    public class TrSheetCertificateData
    {
        public string YEAR { get; set; }
        public string SCHEME { get; set; }
        public string DEGREE { get; set; }
        public string BRANCH_NAME { get; set; }
        public string MONTH_YEAR { get; set; }
        public string NAME { get; set; }
        public string FATHERNAME { get; set; }
        public string GENDER { get; set; }
        public string PIN { get; set; }
        public string CENTRE { get; set; }
        public string INST_NAME { get; set; }
        public string INST_ADDRESS { get; set; }
        public string BRANCH { get; set; }
        public string SUB1_CODE { get; set; }
        public string SUB1_NAME { get; set; }
        public string SUB1_MAX_END_MARKS { get; set; }
        public string SUB1_MAX_SESSIONAL { get; set; }
        public string SUB1_MAX_TOTAL { get; set; }
        public string Sub1_EndMinMarks { get; set; }
        public string Sub1_TotalMinMarks { get; set; }
        public string SUB1_AWARDED_END_MARKS { get; set; }
        public string SUB1_P_F { get; set; }
        public string SUB1_AWARDED_SESSIONAL { get; set; }
        public string SUB1_AWARDED_TOTAL { get; set; }
        public string R1 { get; set; }
        public string SUB2_CODE { get; set; }
        public string SUB2_NAME { get; set; }
        public string SUB2_MAX_END_MARKS { get; set; }
        public string SUB2_MAX_SESSIONAL { get; set; }
        public string SUB2_MAX_TOTAL { get; set; }
        public string Sub2_EndMinMarks { get; set; }
        public string Sub2_TotalMinMarks { get; set; }
        public string SUB2_AWARDED_END_MARKS { get; set; }
        public string SUB2_P_F { get; set; }
        public string SUB2_AWARDED_SESSIONAL { get; set; }
        public string SUB2_AWARDED_TOTAL { get; set; }
        public string R2 { get; set; }
        public string SUB3_CODE { get; set; }
        public string SUB3_NAME { get; set; }
        public string SUB3_MAX_END_MARKS { get; set; }
        public string SUB3_MAX_SESSIONAL { get; set; }
        public string SUB3_MAX_TOTAL { get; set; }
        public string Sub3_EndMinMarks { get; set; }
        public string Sub3_TotalMinMarks { get; set; }
        public string SUB3_AWARDED_END_MARKS { get; set; }
        public string SUB3_P_F { get; set; }
        public string SUB3_AWARDED_SESSIONAL { get; set; }
        public string SUB3_AWARDED_TOTAL { get; set; }
        public string R3 { get; set; }
        public string SUB4_CODE { get; set; }
        public string SUB4_NAME { get; set; }
        public string SUB4_MAX_END_MARKS { get; set; }
        public string SUB4_MAX_SESSIONAL { get; set; }
        public string SUB4_MAX_TOTAL { get; set; }
        public string Sub4_EndMinMarks { get; set; }
        public string Sub4_TotalMinMarks { get; set; }
        public string SUB4_AWARDED_END_MARKS { get; set; }
        public string SUB4_P_F { get; set; }
        public string SUB4_AWARDED_SESSIONAL { get; set; }
        public string SUB4_AWARDED_TOTAL { get; set; }
        public string R4 { get; set; }
        public string SUB5_CODE { get; set; }
        public string SUB5_NAME { get; set; }
        public string SUB5_MAX_END_MARKS { get; set; }
        public string SUB5_MAX_SESSIONAL { get; set; }
        public string SUB5_MAX_TOTAL { get; set; }
        public string Sub5_EndMinMarks { get; set; }
        public string Sub5_TotalMinMarks { get; set; }
        public string SUB5_AWARDED_END_MARKS { get; set; }
        public string SUB5_P_F { get; set; }
        public string SUB5_AWARDED_SESSIONAL { get; set; }
        public string SUB5_AWARDED_TOTAL { get; set; }
        public string R5 { get; set; }
        public string SUB6_CODE { get; set; }
        public string SUB6_NAME { get; set; }
        public string SUB6_MAX_END_MARKS { get; set; }
        public string SUB6_MAX_SESSIONAL { get; set; }
        public string SUB6_MAX_TOTAL { get; set; }
        public string Sub6_EndMinMarks { get; set; }
        public string Sub6_TotalMinMarks { get; set; }
        public string SUB6_AWARDED_END_MARKS { get; set; }
        public string SUB6_P_F { get; set; }
        public string SUB6_AWARDED_SESSIONAL { get; set; }
        public string SUB6_AWARDED_TOTAL { get; set; }
        public string R6 { get; set; }
        public string SUB7_CODE { get; set; }
        public string SUB7_NAME { get; set; }
        public string SUB7_MAX_END_MARKS { get; set; }
        public string SUB7_MAX_SESSIONAL { get; set; }
        public string SUB7_MAX_TOTAL { get; set; }
        public string Sub7_EndMinMarks { get; set; }
        public string Sub7_TotalMinMarks { get; set; }
        public string SUB7_AWARDED_END_MARKS { get; set; }
        public string SUB7_P_F { get; set; }
        public string SUB7_AWARDED_SESSIONAL { get; set; }
        public string SUB7_AWARDED_TOTAL { get; set; }
        public string R7 { get; set; }
        public string SUB8_CODE { get; set; }
        public string SUB8_NAME { get; set; }
        public string SUB8_MAX_END_MARKS { get; set; }
        public string SUB8_MAX_SESSIONAL { get; set; }
        public string SUB8_MAX_TOTAL { get; set; }
        public string Sub8_EndMinMarks { get; set; }
        public string Sub8_TotalMinMarks { get; set; }
        public string SUB8_AWARDED_END_MARKS { get; set; }
        public string SUB8_P_F { get; set; }
        public string SUB8_AWARDED_SESSIONAL { get; set; }
        public string SUB8_AWARDED_TOTAL { get; set; }
        public string R8 { get; set; }
        public string SUB9_CODE { get; set; }
        public string SUB9_NAME { get; set; }
        public string SUB9_MAX_END_MARKS { get; set; }
        public string SUB9_MAX_SESSIONAL { get; set; }
        public string SUB9_MAX_TOTAL { get; set; }
        public string Sub9_EndMinMarks { get; set; }
        public string Sub9_TotalMinMarks { get; set; }
        public string SUB9_AWARDED_END_MARKS { get; set; }
        public string SUB9_P_F { get; set; }
        public string SUB9_AWARDED_SESSIONAL { get; set; }
        public string SUB9_AWARDED_TOTAL { get; set; }
        public string R9 { get; set; }
        public string SUB10_CODE { get; set; }
        public string SUB10_NAME { get; set; }
        public string SUB10_MAX_END_MARKS { get; set; }
        public string SUB10_MAX_SESSIONAL { get; set; }
        public string SUB10_MAX_TOTAL { get; set; }
        public string Sub10_EndMinMarks { get; set; }
        public string Sub10_TotalMinMarks { get; set; }
        public string SUB10_AWARDED_END_MARKS { get; set; }
        public string SUB10_P_F { get; set; }
        public string SUB10_AWARDED_SESSIONAL { get; set; }
        public string SUB10_AWARDED_TOTAL { get; set; }
        public string R10 { get; set; }
        public string SUB11_CODE { get; set; }
        public string SUB11_NAME { get; set; }
        public string SUB11_MAX_END_MARKS { get; set; }
        public string SUB11_MAX_SESSIONAL { get; set; }
        public string SUB11_MAX_TOTAL { get; set; }
        public string Sub11_EndMinMarks { get; set; }
        public string Sub11_TotalMinMarks { get; set; }
        public string SUB11_AWARDED_END_MARKS { get; set; }
        public string SUB11_P_F { get; set; }
        public string SUB11_AWARDED_SESSIONAL { get; set; }
        public string SUB11_AWARDED_TOTAL { get; set; }
        public string R11 { get; set; }
        public string SUB12_CODE { get; set; }
        public string SUB12_NAME { get; set; }
        public string SUB12_MAX_END_MARKS { get; set; }
        public string SUB12_MAX_SESSIONAL { get; set; }
        public string SUB12_MAX_TOTAL { get; set; }
        public string Sub12_EndMinMarks { get; set; }
        public string Sub12_TotalMinMarks { get; set; }
        public string SUB12_AWARDED_END_MARKS { get; set; }
        public string SUB12_P_F { get; set; }
        public string SUB12_AWARDED_SESSIONAL { get; set; }
        public string SUB12_AWARDED_TOTAL { get; set; }
        public string R12 { get; set; }
        public string MAX_END_MARKS_TOTAL { get; set; }
        public string MAX_SESSIONAL_TOTAL { get; set; }
        public string MAX_TOTAL_TOTAL { get; set; }
        public string AWARDED_END_MARKS_TOTAL { get; set; }
        public string AWARDED_SESSIONAL_TOTAL { get; set; }
        public string AWARDED_TOTAL_TOTAL { get; set; }
        public string RESULT { get; set; }
        public string RE { get; set; }

    }

    public class C18OdcTrSheet
    {
        private string industryName;

        public string GetIndustryName()
        {
            return industryName;
        }

        public void SetIndustryName(string value)
        {
            industryName = value;
        }

        public string SNO { get; set; }
        public string ODCNO { get; set; }
        public string CMGNO { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string FNAME { get; set; }
        public string COURSE { get; set; }
        public string CEN { get; set; }
        public string CEN_NAME { get; set; }
        public string CEN_ADDRESS { get; set; }
        public string BR { get; set; }
        public string BRANCH_NAME { get; set; }
        public string MONTH_YEAR { get; set; }
        public string PIN { get; set; }
        public string DURATION { get; set; }
        public string CLASS { get; set; }
        public string MAX_MARKS_1YR { get; set; }
        public string TotalCreditsEarned { get; set; }
        public string TOTAL1 { get; set; }
        public string TOTAL1_25 { get; set; }
        public string MAX_MARKS_3SEM { get; set; }
        public string TOTAL3S { get; set; }
        public string MAX_MARKS_4SEM { get; set; }
        public string TOTAL4S { get; set; }
        public string MAX_MARKS_5SEM { get; set; }
        public string TOTAL5S { get; set; }
        public string MAX_MARKS_6SEM { get; set; }
        public string TOTAL6S { get; set; }
        public string MAX_MARKS_7SEM { get; set; }
        public string TOTAL7S { get; set; }
        public string GRAND_TOTAL { get; set; }
        public string PER { get; set; }
        public string DAY { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string REMARKS { get; set; }
        public bool CertificateIssued { get; set; }
        public string scheme { get; set; }
        public string MAX_MARKS_1SEM { get; set; }
        public string TOTAL1S { get; set; }
        public string TOTAL1S_25 { get; set; }
        public string MAX_MARKS_2SEM { get; set; }
        public string TOTAL2S { get; set; }
        public string TOTAL2S_25 { get; set; }
        public string NameofInstitution { get; set; }
        public string Scheme { get; set; }
        public string ExamMonthYear { get; set; }
        //public string PIN { get; set; }
        public string StudentName { get; set; }
        public string CGPA { get; set; }
        public string FatherName { get; set; }
        public string Division { get; set; }
        public string Semester { get; set; }
        public string SubCode1 { get; set; }
        public string Sub1 { get; set; }
        public string Grade1 { get; set; }
        public string GradePoints1 { get; set; }
        public string Credits1 { get; set; }
        public string SubCode2 { get; set; }
        public string Sub2 { get; set; }
        public string Grade2 { get; set; }
        public string GradePoints2 { get; set; }
        public string Credits2 { get; set; }
        public string SubCode3 { get; set; }
        public string Sub3 { get; set; }
        public string Grade3 { get; set; }
        public string GradePoints3 { get; set; }
        public string Credits3 { get; set; }
        public string SubCode4 { get; set; }
        public string Sub4 { get; set; }
        public string Grade4 { get; set; }
        public string GradePoints4 { get; set; }
        public string Credits4 { get; set; }
        public string SubCode5 { get; set; }
        public string Sub5 { get; set; }
        public string Grade5 { get; set; }
        public string GradePoints5 { get; set; }
        public string Credits5 { get; set; }
        public string SubCode6 { get; set; }
        public string Sub6 { get; set; }
        public string Grade6 { get; set; }
        public string GradePoints6 { get; set; }
        public string Credits6 { get; set; }
        public string SubCode7 { get; set; }
        public string Sub7 { get; set; }
        public string Grade7 { get; set; }
        public string GradePoints7 { get; set; }
        public string Credits7 { get; set; }
        public string SubCode8 { get; set; }
        public string Sub8 { get; set; }
        public string Grade8 { get; set; }
        public string GradePoints8 { get; set; }
        public string Credits8 { get; set; } 
        public string SubCode9 { get; set; }
        public string Sub9 { get; set; }
        public string Grade9 { get; set; }
        public string GradePoints9 { get; set; }
        public string Credits9 { get; set; }
        public string SubCode10 { get; set; }
        public string Sub10 { get; set; }
        public string Grade10 { get; set; }
        public string GradePoints10 { get; set; }
        public string Credits10 { get; set; }
        public string SemesterCreditsEarned { get; set; }
        public string SGPA { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string PhotoPath { get; set; }
        public string Gender { get; set; }
        //public string IndustryName { get; set; }

    }

}
